- id: primary-standalone-keystone
  type: group
  role: [primary-standalone-keystone]
  requires: [deploy_start]
  required_for: [deploy_end, primary-controller, controller]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig, hosts, firewall,
    deploy_start, cluster, keystone-vip, cluster-haproxy, task-keystone]
  parameters:
    strategy:
      type: one_by_one

- id: standalone-keystone
  type: group
  role: [standalone-keystone]
  requires: [deploy_start, primary-standalone-keystone, primary-controller, controller]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig, hosts, firewall,
    deploy_start, cluster, keystone-vip, cluster-haproxy, task-keystone]
  parameters:
    strategy:
      type: parallel

- id: keystone-haproxy
  type: puppet
  groups: [primary-standalone-keystone, standalone-keystone]
  required_for: [task-keystone, deploy_end]
  requires: [deploy_start, keystone-vip, cluster-haproxy]
  parameters:
    puppet_manifest: 'haproxy.pp'
    puppet_modules: '/etc/puppet/modules'
    timeout: 3600

- id: keystone-vip
  type: puppet
  groups: [primary-standalone-keystone, standalone-keystone]
  required_for: [deploy_end]
  requires: [cluster]
  parameters:
    puppet_manifest: 'vip.pp'
    puppet_modules: '/etc/puppet/modules'
    timeout: 3600

- id: task-keystone
  type: puppet
  role: [primary-standalone-keystone, standalone-keystone]
  requires: [hosts, firewall]
  requires: [keystone-haproxy, keystone-vip]
  parameters:
    puppet_manifest: '/etc/puppet/modules/osnailyfacter/modular/keystone/keystone.pp'
    puppet_modules: '/etc/puppet/modules'
    timeout: 3600
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/keystone/keystone_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/keystone/keystone_post.rb

- id: keystone-hiera-override
  type: puppet
  groups: [primary-controller, controller, primary-standalone-keystone, 
    standalone-keystone, cinder, cinder-vmware, compute, ceph-osd, 
    primary-mongo, mongo]
  requires: [globals]
  required_for: [logging]
  parameters:
    puppet_manifest: 'hiera-override.pp'
    puppet_modules: '/etc/puppet/modules'
    timeout: 120
