attributes:
  metadata:
    label: "Keystone settings"
    weight: 90
  yaml_additional_config:
    type: "textarea"
    weight: 52
    value: |
      foo: bar
    label: "Additional config"
    description: "Just put here valid yaml" 
