- id: keystone-hiera-override
  type: puppet
  groups: [primary-controller, controller, primary-keystone, keystone, cinder,
    cinder-vmware, compute, ceph-osd, primary-mongo, mongo]
  requires: [globals]
  required_for: [logging]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/detach-keystone/hiera-override.pp
    puppet_modules: /etc/puppet/modules
    timeout: 120
